version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=your-registry/nextjs-app:buildcache
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
